Add clang-format workflow
accellera-official/systemc-common-practices pull request #6
Opened 2022-07-07 13:30 UTC by aut0

This adds a clang-format CI workflow to check if all code conforms to
the code style.

Signed-off-by: Lukas Jünger <lukas@jngr.org>

2022-07-07 13:48 UTC, markfoodyburton commented
Can you confirm that these files are both being donated under the Apache II license, and that you are permitted by your employer to make this contribution?

2022-07-07 13:49 UTC, aut0 commented
> Can you confirm that these files are both being donated under the Apache II license, and that you are permitted by your employer to make this contribution?

I confirm.

2022-08-09 15:15 UTC, markfoodyburton requested changes

2022-08-09 15:15 UTC, markfoodyburton commented on utils/check_format.sh
> +source=$(find -name "*.h" -or -name "*.cc")
sending?

2022-08-09 15:52 UTC, markfoodyburton approved these changes

2022-08-09 15:52 UTC, merged